version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo building...
      - npm run build
      ## npm run test. Haven't added any test yet
artifacts:
  files:
    - '**/*'
  discard-paths: no
  base-directory: build
